---
- name: Install Spotify
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/homebrew_cask_install.yml
  loop:
    - {package: "spotify", folder: "/Applications/Spotify.app/"}
