---
- name: Install neovim on Linux
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.package:
    name: neovim
    state: present
  become: "{{ become_root }}"

- name: Install neovim on MacOS
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.package:
    name: neovim
    state: present
  become: "{{ become_root }}"

- name: Install silversearch on Linux
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.package:
    name: the_silver_searcher
    state: present

- name: Install silversearch on OSX
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.package:
    name: the_silver_searcher
    state: present

- name: Copy vim config
  ansible.builtin.copy:
    src: files/neovim/.vimrc
    dest: "{{ home_folder }}/"
    mode: preserve

- name: Create neovim config folders
  ansible.builtin.file:
    path: "{{ home_folder }}/.config/nvim/"
    state: directory
    mode: '755'

- name: Copy neovim config
  ansible.builtin.copy:
    src: files/neovim/init.vim
    dest: "{{ home_folder }}/.config/nvim/"
    mode: preserve

- name: Add neovim alias
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} neovim/aliases.sh"
    block: "{{ lookup('file', 'files/neovim/aliases.sh') }}"
