---
- name: Install tools
  ansible.builtin.package:
    name:
      - bat
      - fzf
      - htop
      - jq
      - ripgrep
      - tree
    state: present
  become: "{{ become_root }}"

- name: Change user shell to bash
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: /bin/bash
  become: true

- name: Copy .bash_profile to home folder
  ansible.builtin.copy:
    src: files/.bash_profile
    dest: "{{ home_folder }}"
    mode: preserve

- name: Register .bashrc content
  ansible.builtin.shell: |
    set -o pipefail
    grep -qF "$(cat {{ lookup('file', 'files/.bashrc') }} | tr '\n' '\01')" \
      <<< "$(cat {{ home_folder }}/.bashrc | tr '\n' '\01')"
  register: bashrc_check
  failed_when: false
  changed_when: false

- name: Copy .bashrc to home folder
  ansible.builtin.copy:
    src: files/.bashrc
    dest: "{{ home_folder }}"
    mode: preserve
  when: bashrc_check.rc != 0

- name: Add colorized alias
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} bash_aliases.sh"
    block: "{{ lookup('file', 'files/bash_aliases.sh') }}"

- name: Add pbcopy/pbpaste aliases for Linux
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} bash_aliases_linux.sh"
    block: "{{ lookup('file', 'files/bash_aliases_linux.sh') }}"

- name: Add bash functions to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} bash_functions.sh"
    block: "{{ lookup('file', 'files/bash_functions.sh') }}"

- name: Copy scripts to ~/.bin
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}/.bin/"
    mode: a+x
  with_fileglob:
    - "files/bin/*"
