---
- name: install tools
  package:
    name:
      - bat
      - fzf
      - jq
      - ripgrep
      - tree
    state: present
  become: "{{ become_root }}"

- name: change user shell to bash
  become: true
  user:
    name: "{{ current_user }}"
    shell: /bin/bash

- name: copy .bash_profile to home folder
  copy:
    src: files/.bash_profile
    dest: "{{ home_folder }}"

- name: copy .bashrc to home folder
  copy:
    src: files/.bashrc
    dest: "{{ home_folder }}"

- name: add colorized ls alias when on OSX
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.lineinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# aliases$'
    marker: "# {mark} bash_aliases.sh"
    block: "{{ lookup('file', 'files/bash_aliases.sh') }}"

- name: add bash functions to ~/.bashrc
  blockinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# functions$'
    marker: "# {mark} bash_functions.sh"
    block: "{{ lookup('file', 'files/bash_functions.sh') }}"

- name: copy scripts to ~/.bin
  copy:
    src:  "{{ item }}"
    dest: "{{ home_folder }}/.bin/"
    mode: a+x
  with_fileglob:
    - "files/bin/*"
