---
- name: Change user shell to bash
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: /bin/bash
  become: true

- name: Copy .bash_profile to home folder
  ansible.builtin.copy:
    src: files/.bash_profile
    dest: "{{ home_folder }}"
    mode: preserve

- name: Check ~/.bashrc exists
  ansible.builtin.stat:
    path: "{{ home_folder }}/.bashrc"
  register: bashrc_exists
  failed_when: false
  changed_when: false

# yamllint disable rule:indentation
- name: Register .bashrc content
  when: bashrc_exists.stat.exists is defined and bashrc_exists.stat.exists
  ansible.builtin.shell: |
    set -o pipefail
    grep -qF "$(cat {{ lookup('file', 'files/.bashrc') }} | tr '\n' '\01')" \
      <<< "$(cat {{ home_folder }}/.bashrc | tr '\n' '\01')"
  register: bashrc_content_check
  failed_when: false
  changed_when: false
# yamllint enable rule:indentation

- name: Copy .bashrc to home folder
  when: bashrc_exists.stat.exists is not defined or bashrc_content_check.rc is not defined or bashrc_content_check.rc != 0  # yamllint disable-line rule:line-length
  ansible.builtin.copy:
    src: files/.bashrc
    dest: "{{ home_folder }}"
    mode: preserve

- name: Add bash aliases to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} bash/files/aliases.sh"
    block: "{{ lookup('file', 'files/aliases.sh') }}"

- name: Add bash functions to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} bash/files/functions.sh"
    block: "{{ lookup('file', 'files/functions.sh') }}"

- name: Create ~/.bin/ folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.bin/"
    state: directory
    mode: '755'

- name: Copy scripts to ~/.bin
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: a+x
  loop:
    - {src: files/bin/clipboard.sh, dest: "{{ home_folder }}/.bin/clipboard"}
    - {src: files/bin/colors.sh, dest: "{{ home_folder }}/.bin/colors"}
    - {src: files/bin/passphrase.sh, dest: "{{ home_folder }}/.bin/passphrase"}
