---
- name: Change user shell to bash
  when: not skip_root | bool
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: /bin/bash
  become: true

- name: Copy .bash_profile to home folder
  ansible.builtin.copy:
    src: files/bash/.bash_profile
    dest: "{{ home_folder }}"
    mode: preserve

- name: Check ~/.bash_includes exists
  ansible.builtin.stat:
    path: "{{ home_folder }}/.bash_includes"
  register: bash_includes_exists
  failed_when: false
  changed_when: false

- name: Check ~/.bashrc exists
  ansible.builtin.stat:
    path: "{{ home_folder }}/.bashrc"
  register: bash_configfile_exists
  failed_when: false
  changed_when: false

# yamllint disable rule:line-length
- name: Get base content line count
  when: bash_includes_exists.stat.exists is defined and bash_includes_exists.stat.exists
  ansible.builtin.set_fact:
    bash_base_content: "{{ lookup('file', 'files/bash/.bash_includes') }}"
    bash_base_lines_count: "{{ lookup('file', 'files/bash/.bash_includes') | split('\n') | length }}"

- name: Get first lines from existing file
  when:
    - bash_includes_exists.stat.exists is defined and bash_includes_exists.stat.exists
    - bash_base_lines_count is defined
  ansible.builtin.shell: |
    head -n {{ bash_base_lines_count }} {{ home_folder }}/.bash_includes
  register: bash_existing_first_lines
  changed_when: false

- name: Compare first lines
  when:
    - bash_includes_exists.stat.exists is defined and bash_includes_exists.stat.exists
    - bash_existing_first_lines.stdout is defined
    - bash_base_content is defined
  ansible.builtin.set_fact:
    bash_includes_base_is_equal: "{{ bash_existing_first_lines.stdout == bash_base_content }}"

- name: Copy .bash_includes to home folder
  when: >
    (bash_includes_exists.stat.exists is not defined or not bash_includes_exists.stat.exists) or
    (bash_includes_base_is_equal is defined and not bash_includes_base_is_equal)
  ansible.builtin.copy:
    src: files/bash/.bash_includes
    dest: "{{ home_folder }}"
    mode: preserve
# yamllint enable rule:line-length

- name: Copy .bashrc to home folder
  ansible.builtin.copy:
    src: files/bash/.bashrc
    dest: "{{ home_folder }}"
    mode: preserve

- name: Add bash aliases to ~/.bash_includes
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bash_includes"
    marker: "# {mark} bash/files/aliases.sh"
    block: "{{ lookup('file', 'files/aliases.sh') }}"

- name: Add bash functions to ~/.bash_includes
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bash_includes"
    marker: "# {mark} bash/files/functions.sh"
    block: "{{ lookup('file', 'files/functions.sh') }}"

- name: Create ~/.bin/ folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.bin/"
    state: directory
    mode: '755'

- name: Copy scripts to ~/.bin
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: a+x
  loop:
    - {src: files/bin/clipboard.sh, dest: "{{ home_folder }}/.bin/clipboard"}
    - {src: files/bin/colors.sh, dest: "{{ home_folder }}/.bin/colors"}
    - {src: files/bin/passphrase.sh, dest: "{{ home_folder }}/.bin/passphrase"}
    - {src: files/bin/xkcd.sh, dest: "{{ home_folder }}/.bin/xkcd"}
    - {src: files/bin/todo.sh, dest: "{{ home_folder }}/.bin/todo"}

- name: Create ~/.man/ folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.man/man1/"
    state: directory
    mode: '755'
