---
- name: Include bash
  ansible.builtin.include_tasks:
    file: bash.yml

- name: Include tools
  ansible.builtin.include_tasks:
    file: tools.yml

- name: Copy commands
  ansible.builtin.include_tasks:
    file: shared/install_bins.yml

- name: Add config to ~/.bash_includes
  ansible.builtin.include_tasks:
    file: shared/include_bash_config.yml
