---
- name: Install tools
  when: not skip_root | bool
  ansible.builtin.package:
    name:
      - fzf
      - git-delta
      - htop
      - jq
      - ripgrep
      - tree
      - viu
    state: present
  become: "{{ become_root }}"

- name: Create ~/.local/share/z/ folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.local/share/z/"
    state: directory
    mode: '755'

- name: Copy z.sh to shared folder
  ansible.builtin.copy:
    src: files/z/z.sh
    dest: "{{ home_folder }}/.local/shared/z/"
    mode: preserve

- name: Install z man page
  ansible.builtin.copy:
    src: files/z/z.1
    dest: "{{ home_folder }}/.man/man1"
    mode: preserve
