---
- name: Install neovim
  ansible.builtin.package:
    name: neovim
    state: present
  become: "{{ become_root }}"

- name: Install silversearch
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.package:
    name: silversearcher-ag
    state: present
  become: "{{ become_root }}"

- name: Install silversearch
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.package:
    name: the_silver_searcher
    state: present

- name: Copy vim config
  ansible.builtin.copy:
    src: files/neovim/.vimrc
    dest: "{{ home_folder }}/"
    mode: preserve

- name: Create neovim config folders
  ansible.builtin.file:
    path: "{{ home_folder }}/.config/nvim/"
    state: directory
    mode: '755'

- name: Copy neovim config
  ansible.builtin.copy:
    src: files/neovim/init.vim
    dest: "{{ home_folder }}/.config/nvim/"
    mode: preserve
