language: c

notifications:
    email: false

services:
    - docker

matrix:
    include:
        - os: osx
          env:
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - DIST=ubuntu1604
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - DIST=ubuntu1804
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - DIST=archlinux
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - DIST=fedora
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - TYPE=lint
    allow_failures:
        - os: osx
          env:
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - DIST=ubuntu1804
              - TYPE=build
        - os: linux
          dist: trusty
          env:
              - DIST=fedora
              - TYPE=build

before_install:
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
          docker pull base/archlinux;
          docker pull docker.io/fedora;
          docker pull ubuntu:16.04;
          docker pull ubuntu:18.04;
      fi

script:
    - if [[ "$TYPE" == "lint" ]]; then
          shellcheck -x $(find . -name '*.sh');
      fi
    - if [[ "$TYPE" == "build" && "$TRAVIS_OS_NAME" == "osx" ]]; then
          set    -vx;
          export MYHOME=~;
          export MYUSER=$(whoami);
          DEBUG=1  ./deploy.sh < <(echo -e 'not\\na\\npassword\\n');
      fi
    - if [[ "$TYPE" == "build" && "$TRAVIS_OS_NAME" == "linux" ]]; then
          docker build -f .ci/Dockerfile-${DIST} .;
      fi
