language: c

addons:
    apt:
        packages:
            - flake8

services:
    - docker

before_install:
    - if [[ ! $TRAVIS_OS_NAME == 'osx' ]]; then
          docker pull base/archlinux;
      fi
    - if [[ ! $TRAVIS_OS_NAME == 'osx' ]]; then
          docker pull docker.io/fedora;
      fi
    - if [[ ! $TRAVIS_OS_NAME == 'osx' ]]; then
          docker pull ubuntu:16.04;
      fi
    - if [[ ! $TRAVIS_OS_NAME == 'osx' ]]; then
          docker pull ubuntu:18.04;
      fi

matrix:
    include:
        - os: osx
        - os: linux
          dist: trusty
          env: DIST=ubuntu1804
        - os: linux
          dist: trusty
          env: DIST=ubuntu1604
        - os: linux
          dist: trusty
          env: DIST=fedora
        - os: linux
          dist: trusty
          env: DIST=archlinux

script:
    - if [[ ! $TRAVIS_OS_NAME == 'osx' ]]; then
          flake8 . ;
          shellcheck **/*.sh ;
      fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
          DEBUG=1 ./deploy.sh < <(echo -e 'not\\na\\npassword\\n') ;
      else
          docker build -f Dockerfile-${DIST} . ;
      fi

notifications:
    email: false
