FROM base/archlinux
MAINTAINER Denis Costa

RUN yum update -y
RUN pacman -S --noconfirm sudo

RUN mkdir -p /src/
WORKDIR /src/
COPY . /src/

RUN bash -c "set -vx; USER=root HOME=/root DEBUG=1 /src/deploy.sh < <(echo -e 'not\na\npassword\n')"
