---
- name: Install ffmpeg
  ansible.builtin.package:
    name:
      - ffmpeg
    state: present

- name: Install VLC
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/homebrew_cask_install.yml
  loop:
    - {package: "vlc", folder: "/Applications/VLC.app/"}
