FROM docker.io/fedora
MAINTAINER Denis Costa

RUN yum update -y
RUN yum install sudo

RUN mkdir -p /src/
WORKDIR /src/
COPY . /src/

RUN bash -c "USER=root HOME=/root DEBUG=1 /src/deploy.sh < <(echo -e 'not\na\npassword\n')"
