---
- name: Install homebrew
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"  # yamllint disable-line rule:line-length
  args:
    creates: /opt/homebrew/bin/brew

- name: Install recent bash
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.package:
    name:
      - bash
    state: present

- name: Install homebrew cask apps
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/homebrew_cask_install.yml
  loop:
    - {package: "caffeine", folder: "/Applications/Caffeine.app/"}
    - {package: "dropbox", folder: "/Applications/Dropbox.app"}
    - {package: "firefox", folder: "/Applications/Firefox.app"}
    - {package: "google-chrome", folder: "/Applications/Google Chrome.app/"}
    - {
      package: "password-gorilla",
      folder: "/Applications/Password Gorilla.app/"
    }
    - {package: "slack", folder: "/Applications/Slack.app/"}


- name: Add macos includes to ~/.bashrc
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} macos/files/includes.sh"
    block: "{{ lookup('file', 'files/includes.sh') }}"
