---
- name: Install homebrew
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
      creates: /opt/homebrew/bin/brew

- name: Install recent bash
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew:
      name:
          - bash
      state: present

- name: Add homebrew import
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
      path: "{{ home_folder }}/.bashrc"
      insertafter: '^# imports$'
      marker: "# {mark} homebrew.sh"
      block: "{{ lookup('file', 'files/homebrew.sh') }}"

- name: Include install apps task
  ansible.builtin.include_tasks:
      file: install_apps.yml
  loop:
      - {package: "firefox", folder: "/Applications/Firefox.app"}
      - {package: "google-chrome", folder: "/Applications/Google Chrome.app/"}
      - {package: "password-gorilla", folder: "/Applications/Password Gorilla.app/"}
      - {package: "slack", folder: "/Applications/Slack.app/"}
      - {package: "spotify", folder: "/Applications/Spotify.app/"}
