---
- name: Install homebrew
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
      creates: /opt/homebrew/bin/brew

- name: Add homebrew import
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
      path: "{{ home_folder }}/.bashrc"
      insertafter: '^# imports$'
      marker: "# {mark} homebrew.sh"
      block: "{{ lookup('file', 'files/homebrew.sh') }}"

# - name: Install apps from brew-cask
#   when: ansible_distribution == 'MacOSX'
#   community.general.homebrew_cask:
#     name:
#       - firefox
#       - google-chrome
#       - password-gorilla
#       - slack
#       - spotify
#     state: present
