#!/bin/bash

min_word_length=4
max_word_length=6
password_word_count=5

function show_help {
    echo
    echo "diceware"
    echo
    echo " --min (-n) sets minimum number of characters in the words"
    echo " --max (-m) sets maximum number of characters in the words"
    echo " --count (-c) sets how many word the password will contain"
    echo " --help (-h) shows help message and exit"
    echo
}


while [[ $# > 0 ]]; do
    case $1 in
        --min|-n)
            min_word_length=$2
            shift
        ;;
        --max|-m)
            max_word_length=$2
            shift
        ;;
        --count|-c)
            password_word_count=$2
            shift
        ;;
        --help|-h)
            show_help
            exit 0
        ;;
    esac
    shift
done

elegible_words=$(egrep "^[A-Za-z]{${min_word_length},${max_word_length}}$" /usr/share/dict/words)
word_count=$(wc -w <<< $elegible_words)

for ((i = 0; i < $password_word_count; i++)); do
    echo -n "$(cut -d ' ' -f $(($RANDOM % $word_count + 1)) <<< $elegible_words | tr [:upper:] [:lower:]) "
done

echo
