---
- name: Install git
  ansible.builtin.package:
    name:
      - git
      - tig
    state: present
  become: "{{ become_root }}"

- name: Copy git config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}"
    mode: preserve
  with_fileglob:
    - "files/git/.gitconfig*"

- name: Create git config folders
  ansible.builtin.file:
    path: "{{ home_folder }}/.config/git/git_repo_template/hooks/"
    state: directory
    mode: '755'

- name: Copy Git hooks
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: a+x
  loop:
    - {
      src: files/git/hooks/post-checkout-remove-pyc.sh,
      dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/post-checkout-remove-pyc"  # yamllint disable-line rule:line-length
    }
    - {
      src: files/git/hooks/post-checkout.sh,
      dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/post-checkout"  # yamllint disable-line rule:line-length
    }
    - {
      src: files/git/hooks/pre-commit.sh,
      dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/pre-commit"  # yamllint disable-line rule:line-length
    }

- name: Copy global gitignore
  ansible.builtin.copy:
    src: files/git/ignore_global
    dest: "{{ home_folder }}/.config/git/ignore"
    mode: preserve

- name: Copy git commit message template
  ansible.builtin.copy:
    src: files/git/commit_message_template
    dest: "{{ home_folder }}/.config/git/commit_message_template"
    mode: preserve

- name: Add git functions to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} git/files/functions.sh"
    block: "{{ lookup('file', 'files/functions.sh') }}"
