---
- name: install git
  package:
    name:
      - git
      - tig
    state: present
  become: "{{ become_root }}"

- name: copy git config
  copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}"
  with_fileglob:
    - "files/.gitconfig*"

- name: create git config folders
  file:
    path: "{{ home_folder }}/.config/git/git_repo_template/hooks/"
    state: directory

- name: copy global gitignore
  copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/"
    mode: a+x
  with_fileglob:
    - "files/hooks/*"

- name: copy global gitignore
  copy:
    src: files/ignore
    dest: "{{ home_folder }}/.config/git/ignore"

- name: copy git commit message template
  copy:
    src: files/commit_message_template
    dest: "{{ home_folder }}/.config/git/commit_message_template"

- name: add clean alias
  ansible.builtin.lineinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# aliases$'
    line: alias vim='nvim'

- name: add git function to ~/.bashrc
  blockinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# functions$'
    marker: "# {mark} git_functions.sh"
    block: "{{ lookup('file', 'files/git_functions.sh') }}"
