---
- name: Install git
  ansible.builtin.package:
    name:
      - git
      - tig
    state: present
  become: "{{ become_root }}"

- name: Copy main gitconfig file
  ansible.builtin.copy:
    src: files/git/.gitconfig
    dest: "{{ home_folder }}"
    mode: preserve

- name: Prepare default gitconfig file
  ansible.builtin.template:
    src: "files/git/.gitconfig-default.j2"
    dest: "/tmp/.gitconfig-default"
    mode: preserve

- name: Prepare work gitconfig file
  ansible.builtin.template:
    src: "files/git/.gitconfig-work.j2"
    dest: "/tmp/.gitconfig-work"
    mode: preserve

- name: Copy aux git config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}"
    mode: preserve
  with_fileglob:
    - "/tmp/.gitconfig-*"

- name: Create git config folders
  ansible.builtin.file:
    path: "{{ home_folder }}/.config/git/git_repo_template/hooks/"
    state: directory
    mode: '755'

- name: Copy Git hooks
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: a+x
  loop:
    - {
      src: files/git/hooks/post-checkout-remove-pyc.sh,
      dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/post-checkout-remove-pyc"  # yamllint disable-line rule:line-length
    }
    - {
      src: files/git/hooks/post-checkout.sh,
      dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/post-checkout"  # yamllint disable-line rule:line-length
    }
    - {
      src: files/git/hooks/pre-commit.sh,
      dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/pre-commit"  # yamllint disable-line rule:line-length
    }

- name: Copy global gitignore
  ansible.builtin.copy:
    src: files/git/ignore_global
    dest: "{{ home_folder }}/.config/git/ignore"
    mode: preserve

- name: Copy git commit message template
  ansible.builtin.copy:
    src: files/git/commit_message_template
    dest: "{{ home_folder }}/.config/git/commit_message_template"
    mode: preserve

- name: Add git functions to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} git/files/functions.sh"
    block: "{{ lookup('file', 'files/functions.sh') }}"

- name: Create ~/.bin/ folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.bin/"
    state: directory
    mode: '755'

- name: Copy scripts to ~/.bin
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: a+x
  loop:
    - {
      src: files/bin/workfy-repo.sh,
      dest: "{{ home_folder }}/.bin/workfy-repo"
    }
    - {
      src: files/bin/git-aliases.sh,
      dest: "{{ home_folder }}/.bin/git-aliases"
    }
