---
- name: Install git
  ansible.builtin.package:
    name:
      - git
      - tig
    state: present
  become: "{{ become_root }}"

- name: Copy git config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}"
    mode: preserve
  with_fileglob:
    - "files/.gitconfig*"

- name: Create git config folders
  ansible.builtin.file:
    path: "{{ home_folder }}/.config/git/git_repo_template/hooks/"
    state: directory
    mode: '755'

- name: Copy global gitignore
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}/.config/git/git_repo_template/hooks/"
    mode: preserve
  with_fileglob:
    - "files/hooks/*"

- name: Copy global gitignore
  ansible.builtin.copy:
    src: files/ignore
    dest: "{{ home_folder }}/.config/git/ignore"
    mode: preserve

- name: Copy git commit message template
  ansible.builtin.copy:
    src: files/commit_message_template
    dest: "{{ home_folder }}/.config/git/commit_message_template"
    mode: preserve

- name: Add clean alias
  ansible.builtin.lineinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# aliases$'
    line: alias vim='nvim'

- name: Add git function to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# functions$'
    marker: "# {mark} git_functions.sh"
    block: "{{ lookup('file', 'files/git_functions.sh') }}"
