---
- name: Copy work commands
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/install_bins.yml

- name: Copy work commands that use template
  when:
    - ansible_distribution == 'MacOSX'
    - not skip_secrets | bool
  ansible.builtin.include_tasks:
    file: shared/install_templated_bins.yml

- name: Add work bash includes
  when:
    - ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/include_bash_config.yml

- name: Add work templated bash includes
  when:
    - ansible_distribution == 'MacOSX'
    - not skip_secrets | bool
  ansible.builtin.include_tasks:
    file: shared/include_templated_bash_config.yml
