---
- name: Add work includes to ~/.bashrc
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} work/files/includes.sh"
    block: "{{ lookup('file', 'files/includes.sh') }}"
