---
- name: Add cedar imports
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} cedar.sh"
    block: "{{ lookup('file', 'files/cedar.sh') }}"
