---
- name: Copy work commands
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}/.bin/{{ item | basename | regex_replace('\\.sh$', '') }}"
    mode: a+x
  with_fileglob:
    - "files/*.sh"

- name: Copy new-branch command
  when: not skip_secrets | bool
  ansible.builtin.template:
    src: "files/new-branch.sh.j2"
    dest: "{{ home_folder }}/.bin/new-branch"
    mode: a+x

- name: Copy run-tests command
  when:
    - ansible_distribution == 'MacOSX'
    - not skip_secrets | bool
  ansible.builtin.template:
    src: "files/run-tests.sh.j2"
    dest: "{{ home_folder }}/.bin/run-tests"
    mode: a+x

- name: Add work includes to ~/.bash_includes
  when:
    - ansible_distribution == 'MacOSX'
    - not skip_secrets | bool
  vars:
    work_includes_content: "{{ lookup('template', 'files/includes.sh.j2') }}"
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bash_includes"
    marker: "# {mark} work/files/includes.sh"
    block: "{{ work_includes_content }}"
