---
- name: Prepare work includes file
  ansible.builtin.template:
    src: "files/includes.sh.j2"
    dest: "/tmp/includes.sh"
    mode: preserve

- name: Add work includes to ~/.bashrc
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} work/files/includes.sh"
    block: "{{ lookup('file', '/tmp/includes.sh') }}"
