---
- name: Install terminator
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.package:
    name:
      - terminator
    state: present
  become: "{{ become_root }}"

- name: Create ~/.config/terminator folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.config/terminator"
    state: directory
    mode: '755'

- name: Copy terminator config file
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.copy:
    src: files/terminator/config
    dest: "{{ home_folder }}/.config/terminator/"
    mode: preserve

- name: Install iterm2
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/homebrew_cask_install.yml
  loop:
    - {package: "iterm2", folder: "/Applications/iTerm.app"}

- name: Install tools
  ansible.builtin.package:
    name:
      - bat
      - eza
      - fzf
      - git-delta
      - htop
      - jq
      - ripgrep
      - tmux
      - tree
    state: present
  become: "{{ become_root }}"

- name: Create ~/.local/share/z/ folder
  ansible.builtin.file:
    path: "{{ home_folder }}/.local/share/z/"
    state: directory
    mode: '755'

- name: Copy z.sh to shared folder
  ansible.builtin.copy:
    src: files/z/z.sh
    dest: "{{ home_folder }}/.local/shared/z/"
    mode: preserve

- name: Install z man page
  ansible.builtin.copy:
    src: files/z/z.1
    dest: "{{ home_folder }}/.man/man1"
    mode: preserve

- name: Add terminal functions to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} terminal/files/functions.sh"
    block: "{{ lookup('file', 'files/functions.sh') }}"

- name: Add terminal includes to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} terminal/files/includes.sh"
    block: "{{ lookup('file', 'files/includes.sh') }}"
