---
- name: Install terminator
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.package:
    name:
      - terminator
    state: present
  become: "{{ become_root }}"

- name: Install iterm2
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/homebrew_cask_install.yml
  loop:
    - {package: "iterm2", folder: "/Applications/iTerm.app"}

- name: Install tools
  ansible.builtin.package:
    name:
      - bat
      - eza
      - fzf
      - git-delta
      - htop
      - jq
      - ripgrep
      - tmux
      - tree
    state: present
  become: "{{ become_root }}"

- name: Add bash functions to ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} terminal_functions.sh"
    block: "{{ lookup('file', 'files/terminal_functions.sh') }}"
