---
- name: Install terminator
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.package:
    name:
      - terminator
    state: present
  become: "{{ become_root }}"

- name: Install iterm2
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew_cask:
    name:
      - iterm2
    state: present

- name: Install tmux
  ansible.builtin.package:
    name:
      - tmux
    state: present
  become: "{{ become_root }}"
