---
- name: Register app info
  ansible.builtin.stat:
    path: "{{ item.folder }}"
  register: installation_info

- name: Install apps from brew-cask
  when: not installation_info.stat.exists
  community.general.homebrew_cask:
    name: "{{ item.package }}"
    state: present
  failed_when: false
