---
- name: Copy bin commands
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_folder }}/.bin/{{ item | basename | regex_replace('\\.sh$', '') }}"  # yamllint disable-line rule:line-length
    mode: a+x
  with_fileglob:
    - "files/bin/*.sh"
