#!/bin/bash

set -euo pipefail

export PATH="/usr/local/bin:$PATH"

git_root_dir="$(git rev-parse --git-dir)"

trap 'rm -f "$git_root_dir/$$.tags"' EXIT

git ls-files | ctags --tag-relative -L - -f"$git_root_dir/$$.tags"

mv "$git_root_dir/$$.tags" "$git_root_dir/tags"
