#!/bin/bash

git_root_dir=$(git rev-parse --show-toplevel)

"$git_root_dir"/.git/hooks/ctags > /dev/null 2>&1 &

for hook in "$git_root_dir"/.git/hooks/post-checkout-*; do
    if ! "$hook"; then
        exit 1
    fi
done

exit 0
