#!/bin/sh

which clang-format > /dev/null 2>&1 || \
    (echo "You don't have clang-format installed" && exit 1)

IFS='
'
exitstatus=0
for file in $(git diff --cached --name-only --diff-filter=ACM | grep '.h\|.c'); do
    tmp=$(mktemp)
    git cat-file -p :"$file" | clang-format -style=file > "$tmp"

    if ! diff "$file" "$tmp" > /dev/null 2>&1; then
        echo "$file has formats too fix"
        exitstatus=1
    fi
done

exit $exitstatus
