#!/usr/bin/env ruby
# put this in the file .git/hooks/pre-commit

 require "shellwords"

 puts `git status --porcelain`
 puts "Running Rubocop from #{__FILE__}"

 changed = `git status --porcelain`.
   split("\n").
   map { |l| l.split(" ", 2) }.
   select { |status, _| ["A", "AM", "M"].include?(status) }.
   map { |_, file| file.delete('"') }

 exit if changed.empty?

 parallel = ((File.read(".rubocop.yml").include?("UseCache: false") rescue false) ? "" : " --parallel")
 result = `bundle exec rubocop#{parallel} --force-exclusion #{changed.shelljoin}`

 puts result unless $?.success?
 exit $?.exitstatus
