---
- name: Install apps from brew-cask
  when: ansible_distribution == 'MacOSX'
  community.general.homebrew_cask:
    name:
      - firefox
      - google-chrome
      - password-gorilla
      - slack
      - spotify
    state: present
