---
- name: Include asdf
  ansible.builtin.include_tasks:
    file: asdf.yml

- name: Include sql
  ansible.builtin.include_tasks:
    file: sql.yml

# yamllint disable rule:line-length
- name: Add languages includes to ~/.bash_includes
  vars:
    languages_includes_content: "{{ lookup('template', 'files/includes.sh.j2') }}"
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bash_includes"
    marker: "# {mark} languages/files/includes.sh"
    block: "{{ languages_includes_content }}"
# yamllint enable rule:line-length
