---
- name: Include asdf
  ansible.builtin.include_tasks:
    file: asdf.yml

- name: Include sql
  ansible.builtin.include_tasks:
    file: sql.yml

- name: Add languages includes to ~/.bashrc
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} languages/files/includes-mac.sh"
    block: "{{ lookup('file', 'files/includes-mac.sh') }}"

- name: Add languages includes to ~/.bashrc
  when: ansible_distribution != 'MacOSX'
  ansible.builtin.blockinfile:
    path: "{{ home_folder }}/.bashrc"
    marker: "# {mark} languages/files/includes-linux.sh"
    block: "{{ lookup('file', 'files/includes-linux.sh') }}"
