---
- name: Install DBeaver
  when: ansible_distribution == 'MacOSX'
  ansible.builtin.include_tasks:
    file: shared/homebrew_cask_install.yml
  loop:
    - {package: "dbeaver-community", folder: "/Applications/DBeaver.app/"}
