---
- name: install neovim
  package:
    name: neovim
    state: present
  become: "{{ become_root }}"

- name: install silversearch when in OSX
  when: ansible_distribution == 'MacOSX'
  package:
    name: the_silver_searcher
    state: present

- name: copy vim config
  copy:
    src: files/.vimrc
    dest: "{{ home_folder }}/"

- name: create neovim config folders
  file:
    path: "{{ home_folder }}/.config/nvim/"
    state: directory

- name: copy neovim config
  copy:
    src: files/init.vim
    dest: "{{ home_folder }}/.config/nvim/"

- name: add neovim alias
  ansible.builtin.lineinfile:
    path: "{{ home_folder }}/.bashrc"
    insertafter: '^# aliases$'
    line: alias vim='nvim'

