---
- name: install neovim
  package:
    name: neovim
    state: present
  become: "{{ become_root }}"

- name: install silversearch when in OSX
  when: ansible_distribution == 'MacOSX'
  package:
    name: the_silver_searcher
    state: present

- name: copy vimrc
  copy:
    src: files/.vimrc
    dest: "{{ home_folder }}/"

- name: copy neovim config
  copy:
    src: files/nvim
    dest: "{{ home_folder }}/.config/"

- name: append neovim to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ home_folder }}/.bashrc"
    line: alias vim='nvim'
