---
name: CI
on: [push]  # yamllint disable-line rule:truthy
# yamllint disable rule:indentation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clear up some space on runner
        run: |
          sudo apt-get update
          sudo apt-get --fix-missing
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' |\
            sort -rn |\
            head -n 20
          df -h
          sudo apt-get remove -y '.*llvm.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^libclang.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y '^postgresql-.*'
          sudo apt-get remove -y 'php*'
          sudo apt-get remove -y \
            azure-cli \
            firefox \
            gcc \
            google-chrome-stable \
            google-cloud-cli \
            microsoft-edge-stable \
            mono-devel \
            powershell \
            temurin-21-jdk
          sudo apt-get autoremove -y
          sudo apt-get clean
          rm -rf /usr/share/dotnet/
          df -h
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
# yamllint enable rule:indentation
