---
name: Run playbook
on: [push]  # yamllint disable-line rule:truthy
# yamllint disable rule:indentation
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./
          requirements: requirements.yml
          options: |
            --connection=local
            -i inventory.ini
            --extra-vars "current_user=$$USER home_folder=$$HOME"
            --verbose
  # yamllint enable rule:indentation
